version: '1.0'

services:
  logger:
    container_name: logger
    build: 
      context: .
      dockerfile: docker/docker-logger.Dockerfile
    ports:
      - '1234:1234'
    volumes:
      - ./logs:/usr/src/loggerapp/logs

  nodea:
    container_name: nodeA
    build: 
      context: .
      dockerfile: docker/docker-node.Dockerfile
    environment:
      - NODE=A
    ports:
      - '1235:1235'
    depends_on:
      - logger

  nodeb:
    container_name: nodeB
    build: 
      context: .
      dockerfile: docker/docker-node.Dockerfile
    environment:
      - NODE=B
    ports:
      - '1236:1236'
    depends_on:
      - logger

networks:
  network1:
    name: distributed-nodes
    external: true

# volumes:
#   logs:
    